const userPrompts = require('./prompt.js')
const card = require('./card.js')
const deck = require('./deck.js')
const player = require('./player.js')
const war = require('./gamePlay.js')

userPromts.usernamePrompt()
card.card()
deck.card()
deck.deck()
deck.createNewDeck()
deck.shuffle()
deck.dealHand()
player.player()
war.war()
console.log(game)
war.playGame()